name: Docker Image CI & CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUBUSER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUBPASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adrb-image-na_lab:latest
    - name: Push the Docker image
      run: docker push adrb-image-na_lab:latest
